import { Montserrat } from "next/font/google";
import "./globals.css";

const montserratSans = Montserrat({
  variable: "--font-mont-sans",
  subsets: ["latin"],
});

const montserratMono = Montserrat({
  variable: "--font-mont-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserratSans.className} ${montserratMono.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
